apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: blackbox-alerts
  namespace: monitoring
spec:
  groups:
    - name: blackbox
      rules:
        - alert: UrlDown
          expr: probe_success{job="blackbox"} == 0
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Application URL is down"
            description: "The URL {{ $labels.instance }} is not reachable."
